### ISSUE TITLE
No angular-pouchdb version 0.1

### ISSUE THREAD

**Issue by pel-daniel** [danielzen/ionic-pouchdb-todo#4]
When I run 'bower install' I get the error that there is no angular-pouchdb with version 0.1. 
I think it should be 'ng-pouchdb' instead, but still ng-pouchdb has no tag releases.

Thanks for the repo and the talk you gave at fitc.

**Comment by danielzen** [comment]
I'll look at this, I want this to be easy to setup for others. Thanks.
I also have refactored the underlying angular-pouchdb library used twice, so that may be a problem.

I have used both:
* https://github.com/wspringer/angular-pouchdb
* https://github.com/angular-pouchdb/angular-pouchdb

in different versions. I need to settle on one, and may just absorb one into ng-pouchdb, which as you mentioned has no tag release. Perhaps a 0.0.1 is in order....
